/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', 'Installation', 'Creating Flows', 'Hugging Face Spaces', 'Guidelines'],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: ['How to Upload Examples'],
    },
    {
      type: 'category',
      label: 'GCP Deployment',
      collapsed: false,
      items: ['Deploy Langflow on Google Cloud Platform'],
    },
    {
      type: 'category',
      label: 'Release Notes',
      collapsed: false,
      items: ['Latest Changes'],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: ['How to contribute', 'GitHub Issues', 'Community'],
    },
    
      ],
    };

module.exports = sidebars;